package POJOS;
// Generated 09/11/2019 10:17:12 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Palavra generated by hbm2java
 */
public class Palavra implements java.io.Serializable {

    private Integer id;
    private String palavra;
    private Set expressoes = new HashSet(0);

    public Palavra() {
    }
    
        public Palavra(String palavra, Set expressoes) {
        this.palavra = palavra;
        this.expressoes = expressoes;
    }


    public Palavra(int id, String palavra, Set expressoes) {
        this.palavra = palavra;
        this.expressoes = expressoes;
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPalavra() {
        return this.palavra;
    }

    public void setPalavra(String palavra) {
        this.palavra = palavra;
    }

    public Set getExpressoes() {
        return this.expressoes;
    }

    public void setExpressoes(Set expressoes) {
        this.expressoes = expressoes;
    }

}
